# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learn1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tab3 = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab3.setObjectName("Tab3")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.scrollArea = QtWidgets.QScrollArea(self.tab1)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(70, 130, 561, 20))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 160, 531, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(70, 190, 521, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Tab3.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_2.setObjectName("label_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setGeometry(QtCore.QRect(70, 130, 521, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_5.setGeometry(QtCore.QRect(70, 160, 541, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_2.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_6.setGeometry(QtCore.QRect(70, 190, 631, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.Tab3.addTab(self.tab_2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab3)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_3.setObjectName("label_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_7.setGeometry(QtCore.QRect(70, 130, 711, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_8.setGeometry(QtCore.QRect(70, 160, 681, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_3.addButton(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_9.setGeometry(QtCore.QRect(70, 190, 671, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_3.addButton(self.radioButton_9)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_7)
        self.Tab3.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab4)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_8)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_4.setObjectName("label_4")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_10.setGeometry(QtCore.QRect(70, 130, 681, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_11.setGeometry(QtCore.QRect(70, 160, 681, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup_4.addButton(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_12.setGeometry(QtCore.QRect(70, 190, 711, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup_4.addButton(self.radioButton_12)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_8)
        self.Tab3.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab5)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_5.setObjectName("label_5")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_13.setGeometry(QtCore.QRect(70, 130, 641, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_14.setGeometry(QtCore.QRect(70, 160, 721, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.buttonGroup_5.addButton(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_15.setGeometry(QtCore.QRect(70, 190, 711, 20))
        self.radioButton_15.setObjectName("radioButton_15")
        self.buttonGroup_5.addButton(self.radioButton_15)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_9)
        self.Tab3.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab6)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_10)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_6.setObjectName("label_6")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_16.setGeometry(QtCore.QRect(70, 130, 681, 20))
        self.radioButton_16.setObjectName("radioButton_16")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_17.setGeometry(QtCore.QRect(70, 160, 681, 20))
        self.radioButton_17.setObjectName("radioButton_17")
        self.buttonGroup_6.addButton(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_18.setGeometry(QtCore.QRect(70, 190, 621, 20))
        self.radioButton_18.setObjectName("radioButton_18")
        self.buttonGroup_6.addButton(self.radioButton_18)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_10)
        self.Tab3.addTab(self.tab6, "")
        self.tab7 = QtWidgets.QWidget()
        self.tab7.setObjectName("tab7")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab7)
        self.scrollArea_7.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_11)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_7.setObjectName("label_7")
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_19.setGeometry(QtCore.QRect(70, 130, 661, 20))
        self.radioButton_19.setObjectName("radioButton_19")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_20.setGeometry(QtCore.QRect(70, 160, 691, 20))
        self.radioButton_20.setObjectName("radioButton_20")
        self.buttonGroup_7.addButton(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_21.setGeometry(QtCore.QRect(70, 190, 681, 20))
        self.radioButton_21.setObjectName("radioButton_21")
        self.buttonGroup_7.addButton(self.radioButton_21)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_11)
        self.Tab3.addTab(self.tab7, "")
        self.tab8 = QtWidgets.QWidget()
        self.tab8.setObjectName("tab8")
        self.scrollArea_8 = QtWidgets.QScrollArea(self.tab8)
        self.scrollArea_8.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_12)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_8.setObjectName("label_8")
        self.radioButton_22 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_22.setGeometry(QtCore.QRect(70, 130, 701, 20))
        self.radioButton_22.setObjectName("radioButton_22")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_23.setGeometry(QtCore.QRect(70, 160, 701, 20))
        self.radioButton_23.setObjectName("radioButton_23")
        self.buttonGroup_8.addButton(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_24.setGeometry(QtCore.QRect(70, 190, 711, 20))
        self.radioButton_24.setObjectName("radioButton_24")
        self.buttonGroup_8.addButton(self.radioButton_24)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_12)
        self.Tab3.addTab(self.tab8, "")
        self.tab9 = QtWidgets.QWidget()
        self.tab9.setObjectName("tab9")
        self.scrollArea_9 = QtWidgets.QScrollArea(self.tab9)
        self.scrollArea_9.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_13 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_13.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_13.setObjectName("scrollAreaWidgetContents_13")
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_9.setObjectName("label_9")
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_25.setGeometry(QtCore.QRect(70, 130, 701, 20))
        self.radioButton_25.setObjectName("radioButton_25")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.radioButton_25)
        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_26.setGeometry(QtCore.QRect(70, 160, 721, 20))
        self.radioButton_26.setObjectName("radioButton_26")
        self.buttonGroup_9.addButton(self.radioButton_26)
        self.radioButton_27 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_27.setGeometry(QtCore.QRect(70, 190, 711, 20))
        self.radioButton_27.setObjectName("radioButton_27")
        self.buttonGroup_9.addButton(self.radioButton_27)
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_13)
        self.Tab3.addTab(self.tab9, "")
        self.tab10 = QtWidgets.QWidget()
        self.tab10.setObjectName("tab10")
        self.scrollArea_10 = QtWidgets.QScrollArea(self.tab10)
        self.scrollArea_10.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.scrollAreaWidgetContents_14 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_14.setGeometry(QtCore.QRect(0, 0, 819, 359))
        self.scrollAreaWidgetContents_14.setObjectName("scrollAreaWidgetContents_14")
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_14)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 821, 361))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(50, 10, 751, 101))
        self.label_10.setObjectName("label_10")
        self.radioButton_28 = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_28.setGeometry(QtCore.QRect(70, 130, 691, 20))
        self.radioButton_28.setObjectName("radioButton_28")
        self.buttonGroup_10 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_10.setObjectName("buttonGroup_10")
        self.buttonGroup_10.addButton(self.radioButton_28)
        self.radioButton_29 = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_29.setGeometry(QtCore.QRect(70, 160, 701, 20))
        self.radioButton_29.setObjectName("radioButton_29")
        self.buttonGroup_10.addButton(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_30.setGeometry(QtCore.QRect(70, 190, 701, 20))
        self.radioButton_30.setObjectName("radioButton_30")
        self.buttonGroup_10.addButton(self.radioButton_30)
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_14)
        self.Tab3.addTab(self.tab10, "")
        self.verticalLayout.addWidget(self.Tab3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tab3.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab1), _translate("MainWindow", "Вопрос 1"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_5.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_6.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab_2), _translate("MainWindow", "Вопрос 2"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_7.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_8.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_9.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab3), _translate("MainWindow", "Вопрос 3"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_10.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_11.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_12.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab4), _translate("MainWindow", "Вопрос 4"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_13.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_14.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_15.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab5), _translate("MainWindow", "Вопрос 5"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_16.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_17.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_18.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab6), _translate("MainWindow", "Вопрос 6"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_19.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_20.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_21.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab7), _translate("MainWindow", "Вопрос 7"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_22.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_23.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_24.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab8), _translate("MainWindow", "Вопрос 8"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_25.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_26.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_27.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab9), _translate("MainWindow", "Вопрос 9"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_28.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_29.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_30.setText(_translate("MainWindow", "RadioButton"))
        self.Tab3.setTabText(self.Tab3.indexOf(self.tab10), _translate("MainWindow", "Вопрос 10"))
